### ISSUE TITLE
Better pure Ruby version

### ISSUE THREAD

**Issue by gettalong** [CodeMonkeySteve/fast_xor#10]
Hi,

I have just come across your library and saw in the benchmark file that you compare to a very slow pure Ruby version.

Here is a better version:

~~~ ruby
class String

  def better_xor!(other)
    i = 0
    max = (length < other.length ? length : other.length)
    while i < max
      setbyte(i, getbyte(i) ^ other.getbyte(i))
      i += 1
    end
  end

end
~~~

When running your benchmark script the results are:

~~~
                   user     system      total        real
Ruby       :   4.590000   0.010000   4.600000 (  4.601930)
Ruby better:   1.450000   0.000000   1.450000 (  1.451207)
C (x1000)  :   0.800000   0.000000   0.800000 (  0.800061)
~~~

As you can see the better version is roughly 3x faster than the `slow_xor!` version.

Comparing your C implementation to this better version gives a better insight into how much faster the C version really is.

Cheers,
  Thomas

**Comment by CodeMonkeySteve** [comment]
That's a good optimization, thanks.

Although now that I know, I'll probably deprecate this gem in favor of `xorcist`.
